apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-populate-pvc
  namespace: {{ .Values.namespace }}

spec:
  template:
    spec:
      containers:
        - name: {{ .Release.Name }}-populate-pvc
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - mkdir -p /mnt/data && echo "Populating PVC" &&
              wget -O /mnt/data/image.jpeg https://t4.ftcdn.net/jpg/00/67/24/59/240_F_67245954_ejVa8C414CwJ9X0UadIFu1QEUjeLuFnO.jpg;
          volumeMounts:
          - name: storage
            mountPath: /mnt/data
        restartPolicy: OnFailure
        volumes:
        - name: storage
          persistentVolumeClaim:
              claimName: {{ .Release.Name }}-pvc
