name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: 'YisraelBerman' #${{ github.actor }}
          password: ${{ secrets.gh_token }}

      - name: Extract version from Dockerfile or another file
        id: extract_version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=ghcr.io/yisraelberman/flaskapp:${{ env.VERSION }}
          docker build -t $IMAGE_TAG ./app
          docker push $IMAGE_TAG

      - name: Checkout Helm chart branch
        uses: actions/checkout@v2
        with:
          ref: helm

      - name: Update Helm chart with new image tag
        run: |
          sed -i "s|repository: .*|repository: ghcr.io/yisraelberman/flaskapp|g" mychart/values.yaml
          sed -i "s|tag: .*|tag: \"${{ env.VERSION }}\"|g" mychart/values.yaml
          git config --global user.name "YisraelBerman"
          git config --global user.email "yhsberman@gmail.com"
          git add mychart/values.yaml
          git commit -m "Update image tag to ${{ env.VERSION }}"
          git push origin helm